const { Kpi, KpiStrip, DateStamp, StatusBadge, Button, Progress, Panel, PanelSection, Field, TextLink, Refusal } = window.ArtVentoryDesignSystem_f8dda9;
function ProjectsScreen({ onOpen, selected, onSelect }) {
  const [view,setView]=React.useState('list'); const wide=useWide();
  const P=SY.projects; const now=new Date(SY.now); const day=d=>Math.round((new Date(d)-now)/86400000);
  const folders=[...new Set(P.map(p=>p.folder))];
  const tab=(id,l)=><button key={id} type="button" onClick={()=>setView(id)} style={{background:'none',border:0,borderBottom:view===id?'1px solid #000':'1px solid transparent',padding:'5px 0',fontFamily:'inherit',fontSize:14,letterSpacing:'0.154px',color:view===id?'var(--text-primary)':'var(--text-muted)',cursor:'pointer'}}>{l}</button>;
  const row=p=><div key={p.id} onClick={()=>onSelect(p.id)} style={{display:'grid',gridTemplateColumns:wide?'minmax(0,2fr) minmax(120px,auto) minmax(0,1.1fr) 90px minmax(165px,auto)':'minmax(0,1fr) minmax(110px,auto) minmax(150px,auto)',gap:21,alignItems:'center',padding:'10px 0',borderBottom:'1px solid var(--border-muted)',fontSize:14,letterSpacing:'0.154px',cursor:'pointer',background:selected===p.id?'var(--surface-row-hover)':'transparent'}}>
    <span style={{display:'flex',flexDirection:'column',gap:5,minWidth:0}}><span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.name}</span><span style={{fontSize:13,color:'var(--text-muted)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.type}{wide?'':' · '+p.lead}</span></span>
    <StatusBadge status={p.status}/>
    {wide?<span style={{display:'flex',gap:2}}>{p.cells.map((c,i)=><StatusBadge key={i} status={c} size="bar" style={{flex:1}}/>)}</span>:null}
    {wide?<span style={{fontSize:13,color:'var(--text-secondary)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.lead}</span>:null}
    <DateStamp date={p.due} now={SY.now}/>
  </div>;
  const cell=(p,i)=>{const s=p.cells[i]; const m={done:'var(--status-done)',progress:'var(--status-progress)',risk:'var(--status-risk)',blocked:'var(--status-blocked)',notstarted:'var(--status-notstarted)',build:'var(--source-build)'}[s]; const soft={done:'var(--status-done-soft)',progress:'var(--status-progress-soft)',risk:'var(--status-risk-soft)',blocked:'var(--status-blocked-soft)',notstarted:'transparent',build:'var(--source-build-soft)'}[s]; const d=day(p.dates[i]);
    return <div key={i} style={{borderLeft:'1px solid var(--border-muted)',padding:'5px 10px',minHeight:52,background:soft,display:'flex',flexDirection:'column',gap:5,justifyContent:'space-between',boxSizing:'border-box'}}><span style={{display:'flex',alignItems:'center',gap:5,fontSize:13,letterSpacing:'0.15px',color:s==='notstarted'?'var(--text-muted)':m}}><span style={{width:5,height:5,background:m}}/>{s==='done'?'Done':s==='progress'?'In progress':s==='risk'?'At risk':s==='blocked'?'Blocked':s==='build'?'Build':'—'}</span><span style={{fontSize:13,fontVariantNumeric:'tabular-nums',color:s==='notstarted'?'var(--text-muted)':'var(--text-secondary)'}}>{p.dates[i].slice(5).replace('-','/')}{s!=='done'&&s!=='notstarted'?' · '+(d<0?-d+'d late':'in '+d+'d'):''}</span>{i===p.phase&&p.note?<span style={{fontSize:13,color:m,lineHeight:1.2}}>{p.note}</span>:null}</div>;};
  return <div>
    <PageHead kicker="Atlanta · 6 projects" title="Projects" actions={<><Button variant="outline" size="sm">Filter</Button><Button size="sm">+ New project</Button></>}>
      <KpiStrip><Kpi value={P.filter(p=>p.status!=='done').length} label="Active"/><Kpi value={P.filter(p=>day(p.due)>=0&&day(p.due)<30).length} label="Due this month"/><Kpi value={P.filter(p=>p.status==='blocked').length} label="Blocked" tone="blocked"/><Kpi value="38" label="Open checklist items" hint="9 required"/></KpiStrip>
      <div style={{display:'flex',gap:21,borderBottom:'1px solid var(--border-muted)'}}>{tab('list','List')}{tab('board','Board')}{tab('calendar','Calendar')}{tab('matrix','Matrix')}</div>
    </PageHead>
    {view==='list'?<div style={{display:'flex',flexDirection:'column',gap:42}}>{folders.map(f=><section key={f}><div style={{display:'flex',justifyContent:'space-between',borderBottom:'1px solid var(--border-hairline)',paddingBottom:10,fontSize:18,lineHeight:1.15,letterSpacing:'0.198px'}}><span>{f}</span><span style={{fontSize:13,color:'var(--text-muted)'}}>{P.filter(p=>p.folder===f).length}</span></div>{P.filter(p=>p.folder===f).map(row)}</section>)}</div>:null}
    {view==='matrix'?<div style={{maxWidth:'100%',overflowX:'auto'}}><div style={{minWidth:900}}><div style={{display:'grid',gridTemplateColumns:'minmax(0,1.4fr) repeat(6,minmax(0,1fr))',borderBottom:'1px solid var(--border-hairline)',fontSize:13,letterSpacing:'0.143px',color:'var(--text-secondary)'}}><span style={{padding:'5px 0'}}>Project</span>{SY.phases.map(ph=><span key={ph} style={{padding:'5px 10px',borderLeft:'1px solid var(--border-muted)'}}>{ph}</span>)}</div>{P.map(p=><div key={p.id} onClick={()=>onSelect(p.id)} style={{display:'grid',gridTemplateColumns:'minmax(0,1.4fr) repeat(6,minmax(0,1fr))',borderBottom:'1px solid var(--border-muted)',cursor:'pointer'}}><div style={{padding:'10px 21px 10px 0',display:'flex',flexDirection:'column',gap:5,fontSize:14,minWidth:0}}><span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{p.name}</span><span style={{fontSize:13,color:'var(--text-muted)'}}>{p.lead} · <DateStamp date={p.due} now={SY.now} showRelative={false} style={{fontSize:13}}/></span></div>{SY.phases.map((_,i)=>cell(p,i))}</div>)}</div></div>:null}
    {view==='board'||view==='calendar'?<div style={{border:'1px dashed var(--border-muted)',padding:42,fontSize:13,color:'var(--text-muted)'}}>{view==='board'?'Board view — columns by phase step. Not yet built this pass.':'Calendar view — month grid of project and phase due dates. Not yet built this pass.'}</div>:null}
  </div>;
}
function ProjectPanel({ id, onClose, onOpen }) {
  const p=SY.projects.find(x=>x.id===id); if(!p) return null;
  return <Panel kicker={p.type+' · '+p.folder} title={p.name} onClose={onClose} footer={<><Button size="sm" onClick={()=>onOpen(p.id)}>Open project</Button><Button size="sm" variant="ghost">Archive</Button></>} style={{position:'sticky',top:0,height:'100vh'}}>
    <PanelSection title="Status"><Field label="Status"><StatusBadge status={p.status}/></Field><Field label="Phase">{SY.phases[p.phase]}</Field><Field label="Lead">{p.lead}</Field><Field label="Opens"><DateStamp date={p.due} now={SY.now}/></Field></PanelSection>
    {p.note?<Refusal title={p.note} action={<TextLink href="#" arrow onClick={e=>{e.preventDefault();onOpen(p.id);}}>Go to checklist</TextLink>}/>:null}
    <PanelSection title="Phases">{SY.phases.map((ph,i)=><div key={ph} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,padding:'5px 0',borderBottom:'1px solid var(--border-muted)',fontSize:13}}><span style={{display:'flex',gap:10,alignItems:'center'}}><StatusBadge status={p.cells[i]} size="dot"/>{ph}</span><DateStamp date={p.dates[i]} now={SY.now} clock="phase" showRelative={p.cells[i]!=='done'}/></div>)}</PanelSection>
  </Panel>;
}
Object.assign(window,{ProjectsScreen,ProjectPanel});