const { Kpi, KpiStrip, StatusBadge, SourceBadge, Button, Refusal, EmptyState, ImageBlock, ImageGrid, TextLink, Panel, PanelSection, Field } = window.ArtVentoryDesignSystem_f8dda9;
const money=n=>n?('$'+n.toLocaleString()):'—';
function ScheduleScreen({ selected, onSelect, project }) {
  const [view,setView]=React.useState('table'); const wide=useWide(); const S=SY.schedule; const all=S.flatMap(g=>g.rows);
  const tot=all.reduce((a,r)=>a+r.unit*r.qty,0); const short=all.filter(r=>r.short);
  const th={fontSize:13,letterSpacing:'0.143px',color:'var(--text-secondary)',padding:'5px 21px 5px 0',textAlign:'left',fontWeight:400};
  const td={padding:'10px 21px 10px 0',fontSize:14,letterSpacing:'0.154px',verticalAlign:'middle',fontVariantNumeric:'tabular-nums'};
  const thumb=r=><ImageBlock width={42} height={42} placeholder={r.source==='build'?'spec':'photo'} style={r.source==='build'?{border:'1px dashed var(--border-muted)',color:'var(--text-muted)'}:{color:'var(--text-muted)'}}/>;
  return <div>
    <PageHead kicker={project.name+' · FF&E'} title="Schedule" actions={<><Button variant="outline" size="sm">Print list</Button><Button size="sm">+ Add item</Button></>}>
      <KpiStrip><Kpi value={all.reduce((a,r)=>a+r.qty,0)} label="Items" hint={all.length+' lines · '+S.length+' rooms'}/><Kpi value={all.filter(r=>r.source==='warehouse').length} label="From warehouse"/><Kpi value={all.filter(r=>r.source==='purchase').length} label="To purchase"/><Kpi value={money(tot)} label="Total spend"/><Kpi value={short.length} label="Short" tone={short.length?'risk':undefined} hint={short.length?short.map(r=>r.tag).join(', '):undefined}/></KpiStrip>
      {short.map(r=><Refusal key={r.id} tone="short" title={'Warehouse has '+(r.qty-r.short)+' free of '+r.qty+' '+r.item.toLowerCase()+' — this leaves you '+r.short+' short before pull day'} action={<span style={{display:'flex',gap:10,flexWrap:'wrap'}}><Button size="sm" variant="outline">{'Purchase '+r.short}</Button><Button size="sm" variant="ghost">{'Reduce to '+(r.qty-r.short)}</Button></span>}/>)}
      <div style={{display:'flex',gap:21,borderBottom:'1px solid var(--border-muted)'}}>{[['table','Table'],['gallery','Gallery']].map(([id,l])=><button key={id} type="button" onClick={()=>setView(id)} style={{background:'none',border:0,borderBottom:view===id?'1px solid #000':'1px solid transparent',padding:'5px 0',fontFamily:'inherit',fontSize:14,letterSpacing:'0.154px',color:view===id?'var(--text-primary)':'var(--text-muted)',cursor:'pointer'}}>{l}</button>)}</div>
    </PageHead>
    <div style={{display:'flex',flexDirection:'column',gap:42}}>{S.map(g=>{const sub=g.rows.reduce((a,r)=>a+r.unit*r.qty,0); return <section key={g.room}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',gap:21,borderBottom:'1px solid var(--border-hairline)',paddingBottom:10,fontSize:18,lineHeight:1.15,letterSpacing:'0.198px'}}><span style={{minWidth:0,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{g.room}</span><span style={{flex:'0 0 auto',fontSize:13,color:'var(--text-muted)',fontVariantNumeric:'tabular-nums',whiteSpace:'nowrap'}}>{g.rows.reduce((a,r)=>a+r.qty,0)} items · {money(sub)}</span></div>
      {view==='table'?<div style={{maxWidth:'100%',overflowX:'auto'}}><table style={{width:'100%',minWidth:'max-content',borderCollapse:'collapse'}}><thead><tr style={{borderBottom:'1px solid var(--border-muted)'}}>{wide?<th style={{...th,width:42}}></th>:null}<th style={{...th,width:70}}>Tag</th><th style={th}>Item</th><th style={{...th,textAlign:'right',width:50}}>Qty</th><th style={th}>Source</th><th style={{...th,textAlign:'right',width:90}}>Unit</th><th style={{...th,textAlign:'right',width:100}}>Total</th><th style={{...th,width:130}}>Status</th></tr></thead><tbody>{g.rows.map(r=><tr key={r.id} onClick={()=>onSelect(r.id)} style={{borderBottom:'1px solid var(--border-muted)',cursor:'pointer',background:selected===r.id?'var(--surface-row-hover)':'transparent'}}>
        {wide?<td style={td}>{thumb(r)}</td>:null}<td style={{...td,color:'var(--text-muted)',fontSize:13,whiteSpace:'nowrap'}}>{r.tag}</td><td style={td}>{r.item}</td><td style={{...td,textAlign:'right'}}>{r.qty}{r.short?<span style={{color:'var(--status-risk)',fontSize:13}}> · {r.short} short</span>:null}</td><td style={td}><SourceBadge source={r.source} detail={r.detail}/></td><td style={{...td,textAlign:'right',color:r.unit?'var(--text-primary)':'var(--text-muted)'}}>{money(r.unit)}</td><td style={{...td,textAlign:'right',color:r.unit?'var(--text-primary)':'var(--text-muted)'}}>{money(r.unit*r.qty)}</td><td style={td}><StatusBadge status={r.status} label={r.status==='progress'?'Ordered':r.status==='done'?'Delivered':r.status==='risk'?'Short':r.status==='notstarted'?'Needed':undefined}/></td></tr>)}</tbody></table></div>
      :<ImageGrid min={200} style={{paddingTop:21}}>{g.rows.map(r=><div key={r.id} onClick={()=>onSelect(r.id)} style={{cursor:'pointer',display:'flex',flexDirection:'column',gap:10,minWidth:0,outline:selected===r.id?'1px solid #000':'none',outlineOffset:5}}><EmptyState ratio="1 / 1" what={r.source==='build'?'Drawing from spec':'Photo — team recognises it by sight'}/><div style={{display:'flex',justifyContent:'space-between',gap:10,fontSize:14,minWidth:0}}><span style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{r.item}</span><span style={{flex:'0 0 auto',fontVariantNumeric:'tabular-nums',color:'var(--text-muted)'}}>×{r.qty}</span></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,minWidth:0}}><SourceBadge source={r.source}/><StatusBadge status={r.status} size="dot"/></div></div>)}</ImageGrid>}
    </section>;})}</div>
  </div>;
}
function RowPanel({ id, onClose }) {
  const r=SY.schedule.flatMap(g=>g.rows).find(x=>x.id===id); if(!r) return null;
  return <Panel kicker={'Schedule row · '+r.tag} title={r.item} onClose={onClose} footer={<><Button size="sm" variant="outline">Edit</Button><Button size="sm" variant="ghost">Remove</Button></>} style={{position:'sticky',top:0,height:'100vh'}}>
    <EmptyState ratio="4 / 3" what={r.source==='build'?'Drawing pulls live from the board':'Photo goes here'} action={<TextLink href="#" arrow style={{fontSize:13}}>{r.source==='build'?'Open spec':'Upload'}</TextLink>}/>
    <PanelSection title="Source"><SourceBadge source={r.source} detail={r.detail}/>{r.short?<span style={{fontSize:13,color:'var(--status-risk)'}}>{r.qty-r.short} on hand − {r.qty-r.short} reserved = 0 free · {r.short} short</span>:null}</PanelSection>
    <PanelSection title="Details"><Field label="Quantity">{r.qty}</Field><Field label="Unit">{money(r.unit)}</Field><Field label="Total">{money(r.unit*r.qty)}</Field><Field label="Status"><StatusBadge status={r.status}/></Field><Field label="Installs">{SY.schedule.find(g=>g.rows.includes(r)).room}</Field></PanelSection>
  </Panel>;
}
Object.assign(window,{ScheduleScreen,RowPanel});